---
version: '3'
services:

# START SERVICE controlplane.modeco
  controlplane:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.controlplane.modeco:v2.0.11
    environment: [${CONTROLPLANE_MODECO_ENVIRONMENT}]
    command: [${CONTROLPLANE_MODECO_COMMAND}]
    volumes: ['/etc:/hostfs/etc:ro','/var/run/docker.sock:/var/run/docker.sock','controlplane_repos_${CONTECO_DC_GLOBAL_STACKNAMES}:/conteco/pwd']
    ports: []
    networks: []
    deploy:
      mode: ${CONTROLPLANE_MODECO_DEPLOY_MODE}
      resources:
        limits:
          memory: '${CONTROLPLANE_MODECO_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTROLPLANE_MODECO_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTROLPLANE_MODECO_COMPOSE_EXTENSIONS}
# END SERVICE controlplane.modeco

networks: {}
volumes: {controlplane_repos_${CONTECO_DC_GLOBAL_STACKNAMES}: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
